name: Build

on:
  workflow_dispatch:
    inputs:
      device:
        description: "Device Type"
        required: true
        default: 'uz801'
        type: choice
        options:
          - uz801
          - uf896
          - ufi001c
      release:
        description: "OS Version"
        required: true
        default: 'v25.12'
        type: choice
        options:
          - v25.12
          - v25.06
          - v24.12
          - v24.06
      arch:
        description: "Target architecture"
        required: true
        default: 'armv7'
        type: choice
        options:
          - armv7
          - armv8

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        with:
          submodules: true

      - name: Install dependencies
        run: sudo sh -e scripts/install_deps.sh

      - name: Build hyp and aboot firmware
        run: |
          case "${{ inputs.device }}" in
            uz801)
              DESCR="yiming,uz801-v3"
              ;;
            uf896)
              DESCR="thwc,uf896"
              ;;
            ufi001c)
              DESCR="thwc,ufi001c"
              ;;
            *)
              echo "Unsupported device: $TYPEDEV" >&2
              exit 1
              ;;
          esac

          echo "Description: ${DESCR}"
          make -C src/qhypstub CROSS_COMPILE=aarch64-linux-gnu-

          # patch to reduce mmc speed as some boards have intermittent failures when
          # inititalizing the mmc (maybe due to using old/recycled flash chips)
          echo 'DEFINES += USE_TARGET_HS200_CAPS=1' >> src/lk2nd/project/lk1st-msm8916.mk
          echo "make -C src/lk2nd LK2ND_BUNDLE_DTB=\"msm8916-512mb-mtp.dtb\" LK2ND_COMPATIBLE=\"${DESCR}\" TOOLCHAIN_PREFIX=arm-none-eabi- lk1st-msm8916 -j$(nproc)"
          make -C src/lk2nd \
            LK2ND_BUNDLE_DTB="msm8916-512mb-mtp.dtb" \
            LK2ND_COMPATIBLE="${DESCR}" \
            TOOLCHAIN_PREFIX=arm-none-eabi- \
            lk1st-msm8916 -j$(nproc)
          
          # test sign
          mkdir -p files
          src/qtestsign/qtestsign.py hyp src/qhypstub/qhypstub.elf \
            -o files/hyp.mbn
          src/qtestsign/qtestsign.py aboot src/lk2nd/build-lk1st-msm8916/emmc_appsboot.mbn \
            -o files/aboot.mbn

      - name: Extract MSM8916 firmware
        run: sudo sh -e scripts/extract_fw.sh

      - name: Create rootfs
        run: sudo RELEASE_INPUT="${{ inputs.release }}" DEV_TYPE="${{ inputs.device }}" sh -e scripts/alpine_rootfs.sh

      - name: Create images
        run: sudo sh -e scripts/build_images.sh
          
      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: uz801-alpine 
          path: files/*

      - name: Generate release tag
        id: version
        run: |   
          TAG_NAME=$(echo "Alpine-${{ inputs.release }}-${{ inputs.arch }}-${{ inputs.device }}_#${{ github.run_number }}")
          gh release delete "$TAG_NAME" --yes || true
          git tag -d "$TAG_NAME" 2>/dev/null || true
          git push --delete origin "$TAG_NAME" 2>/dev/null || true
          git tag $TAG_NAME
          git push origin $TAG_NAME
          echo "TAG_NAME=$TAG_NAME" >> $GITHUB_OUTPUT
          
      - name: Releases 
        uses: softprops/action-gh-release@v2 
        with:
          name: ${{ inputs.device }}_alpine-${{ inputs.release }}-${{ inputs.arch }}
          tag_name: ${{ steps.version.outputs.TAG_NAME }}
          files: files/*
