name: Build

on:
  workflow_dispatch:
    inputs:
      device:
        description: "Device Type"
        required: true
        default: 'uz801'
        type: choice
        options:
          - uz801
          - uf896
      release:
        description: "OS Version"
        required: true
        default: 'v25.12'
        type: choice
        options:
          - v25.12
          - v25.06
          - v24.12
          - v24.06
      arch:
        description: "Target architecture"
        required: true
        default: 'armv7'
        type: choice
        options:
          - armv7
          - armv8

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        with:
          submodules: true

      - name: Install dependencies
        run: sudo sh -e scripts/install_deps.sh

      - name: Build hyp and aboot firmware
        run: sudo DEV_TYPE="${{ inputs.device }}" sh -e scripts/build_hyp_aboot.sh

      - name: Extract MSM8916 firmware
        run: sudo sh -e scripts/extract_fw.sh

      - name: Create rootfs
        run: sudo RELEASE_INPUT="${{ inputs.release }}" sh -e scripts/alpine_rootfs.sh

      - name: Create images
        run: sudo sh -e scripts/build_images.sh
          
      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: uz801-alpine 
          path: files/*

      - name: Generate release tag
        id: version
        run: |   
          TAG_NAME=$(echo "Alpine-v${{ inputs.release }}-${{ inputs.arch }}-${{ inputs.device }}__${{ github.run_number }}")
          gh release delete "$TAG_NAME" --yes || true
          git tag -d "$TAG_NAME" 2>/dev/null || true
          git push --delete origin "$TAG_NAME" 2>/dev/null || true
          git tag $TAG_NAME
          git push origin $TAG_NAME
          echo "TAG_NAME=$TAG_NAME" >> $GITHUB_OUTPUT
          
      - name: Releases 
        uses: softprops/action-gh-release@v2 
        with:
          name: uz801-alpine-v${{ inputs.release }}-${{ inputs.arch }}-${{ inputs.device }}
          tag_name: ${{ steps.version.outputs.TAG_NAME }}
          files: files/*
